stages:
  - build
  - test-plan
  - prod-plan
  - build-image
  - deploy-image

variables:
  UV_VERSION: "0.11.18"
  UV_LINK_MODE: "copy"
  UV_CACHE_DIR: .uv-cache
  PYTHON_VERSION: "3.12"
  UV_IMAGE_TYPE: "trixie-slim"

  SQLMESH_CACHE_DIR: .cache
  SQLMESH_CLOUD_SQL_INSTANCE_CONNECTION_STRING_ID: "sqlmesh-cloud-sql-instance-prod-connection-string"
  SQLMESH_CLOUD_SQL_USER_SECRET_ID: "sqlmesh-cloud-sql-prod-user"
  SQLMESH_CLOUD_SQL_PASSWORD_SECRET_ID: "sqlmesh-cloud-sql-prod-user-password"

  GOOGLE_PROJECT_ID: "devops-test"
  GOOGLE_REGION: "us-central1"
  GCLOUD_VERSION: "569.0.0"
  SERVICE_ACCOUNT_EMAIL: "sqlmesh-plan@devops-test.iam.gserviceaccount.com"

  DOCKER_VERSION: "29.5.2"

default:
  image: ghcr.io/astral-sh/uv:${UV_VERSION}-python${PYTHON_VERSION}-${UV_IMAGE_TYPE}

.gcp_credentials:
  before_script:
    - printf "%s" "$GCP_SERVICE_ACCOUNT" | tee google-credentials.json >/dev/null
    - export GOOGLE_APPLICATION_CREDENTIALS=google-credentials.json

.sqlmesh_credentials:
  before_script:
    - !reference [.gcp_credentials, before_script]
    - export GOOGLE_PROJECT_ID=$GOOGLE_PROJECT_ID
    - export SQLMESH_CLOUD_SQL_INSTANCE_CONNECTION_STRING_SECRET_ID=$SQLMESH_CLOUD_SQL_INSTANCE_CONNECTION_STRING_ID
    - export SQLMESH_CLOUD_SQL_USER_SECRET_ID=$SQLMESH_CLOUD_SQL_USER_SECRET_ID
    - export SQLMESH_CLOUD_SQL_PASSWORD_SECRET_ID=$SQLMESH_CLOUD_SQL_PASSWORD_SECRET_ID

.gcp_gcloud_auth:
  before_script:
    - !reference [.gcp_credentials, before_script]
    - gcloud auth activate-service-account --key-file=google-credentials.json
    - gcloud config set project $GOOGLE_PROJECT_ID

.gcr_docker_login:
  before_script:
    - !reference [.gcp_credentials, before_script]
    - cat google-credentials.json | docker login -u _json_key --password-stdin https://gcr.io

# Build Feature Branches that don't have an MR open
BuildFeatureBranch:
  stage: build
  rules:
    - if: '$CI_OPEN_MERGE_REQUESTS == ""'
      when: always
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: never
    - when: never
  script:
    - |
      echo "Building Feature Branch..."
      uv lock --check
      uv sync --frozen --no-dev
      uv cache prune --ci
  cache:
    key:
      files:
        - uv.lock
    paths:
      - .venv/
      - $UV_CACHE_DIR/
    policy: pull-push

# Builds for Open MRs and Main Branch
BuildMergeRequestBranch:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - when: never
  script:
    - |
      echo "Building MR Branch..."
      uv lock --check
      uv sync --frozen --no-dev
      uv cache prune --ci
  cache:
    key:
      files:
        - uv.lock
    paths:
      - .venv/
      - $UV_CACHE_DIR/
    policy: pull-push

# Run SQLMesh Test Plan of last 30 days for Open MR Branches
TestPlanMergeRequestBranch:
  stage: test-plan
  extends: .sqlmesh_credentials
  retry: 1
  needs:
    - job: BuildMergeRequestBranch
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: on_success
  cache:
    - key:
        files:
          - uv.lock
      paths:
        - .venv/
        - $UV_CACHE_DIR/
      policy: pull
    - key: "${CI_COMMIT_REF_SLUG}-sqlmesh-cache"
      paths:
        - $SQLMESH_CACHE_DIR
      policy: pull-push
      fallback_keys:
        - "main-sqlmesh-cache"
  script:
    - echo "Testing Plan for MR Branch..."
    - uv lock --check
    - uv sync --frozen --no-dev
    - uv run --no-sync -- sqlmesh plan dev_MR_$CI_MERGE_REQUEST_IID \
        --no-prompts \
        --auto-apply \
        -s "$(date -d '30 days ago' '+%Y-%m-%d')"

ProdPlan:
  stage: prod-plan
  extends: .sqlmesh_credentials
  retry: 1
  needs:
    - job: BuildMergeRequestBranch
  only:
    - main
  cache:
    - key:
        files:
          - uv.lock
      paths:
        - .venv/
        - $UV_CACHE_DIR/
      policy: pull
    - key: "main-sqlmesh-cache"
      paths:
        - $SQLMESH_CACHE_DIR
      policy: pull-push
  script:
    - echo "Executing Plan on Prod..."
    - uv lock --check
    - uv sync --frozen --no-dev
    - uv run --no-sync -- sqlmesh plan prod --no-prompts --auto-apply

BuildDockerImageBranch:
  stage: build-image
  image: docker:${DOCKER_VERSION}
  services:
    - name: docker:${DOCKER_VERSION}-dind
      alias: docker
      command: ["--tls=false"]
      variables:
        HEALTHCHECK_TCP_PORT: "2375"
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
  before_script:
    - !reference [.gcr_docker_login, before_script]
    - docker info
  only:
    - main
  script:
    - echo "Building Docker Image for Branch $CI_COMMIT_SHORT_SHA..."
    - docker build --platform linux/amd64 -t gcr.io/$GOOGLE_PROJECT_ID/$SERVICE_NAME:$CI_COMMIT_SHORT_SHA .
    - docker push gcr.io/$GOOGLE_PROJECT_ID/$SERVICE_NAME:$CI_COMMIT_SHORT_SHA

DeployDockerImageBranch:
  stage: deploy
  image: gcr.io/google.com/cloudsdktool/google-cloud-cli:${GCLOUD_VERSION}-stable
  extends: .gcp_gcloud_auth
  retry: 2
  needs:
    - job: BuildDockerImageBranch
    - job: ProdPlan
  only:
    - main
  script:
    - echo "Deploying Docker Image for Branch $CI_COMMIT_SHORT_SHA..."
    - |
      gcloud run jobs update sqlmesh-run \
        --image gcr.io/$GOOGLE_PROJECT_ID/$SERVICE_NAME:$CI_COMMIT_SHORT_SHA \
        --region $GOOGLE_REGION \
        --service-account $SERVICE_ACCOUNT_EMAIL \
        --args "commands.run"
    - |
      gcloud run jobs update sqlmesh-janitor \
        --image gcr.io/$GOOGLE_PROJECT_ID/$SERVICE_NAME:$CI_COMMIT_SHORT_SHA \
        --region $GOOGLE_REGION \
        --service-account $SERVICE_ACCOUNT_EMAIL \
        --args "commands.janitor"
    - |
      gcloud run jobs update sqlmesh-export \
        --image gcr.io/$GOOGLE_PROJECT_ID/$SERVICE_NAME:$CI_COMMIT_SHORT_SHA \
        --region $GOOGLE_REGION \
        --service-account $SERVICE_ACCOUNT_EMAIL \
        --args "commands.export"