[project]
name = "sqlmesh-test-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pendulum>=3.2.0",
    "pydantic-settings>=2.14.1",
    "sqlmesh[bigquery,gcppostgres,slack]>=0.231.0",
]

[tool.ruff]
target-version = "py312"
line-length = 100
lint.extend-select = [
    "A",     # Builtins
    "DTZ",   # Datetime
    "SIM",   # Simplify
    "I",     # Isort Imports
    "S",     # Bandit
    "PT",    # Pytest
    "B",     # BugBear
    "N",     # Naming Conventions
    "RUF",   # Ruff Specific Rules
    "PTH",   # Pathlib
    "ARG",   # Unused Args
    "C4",    # Force Current List Comprehensions
    "RET"    # Return Checks
]

[tool.ruff.lint.per-file-ignores]
"test_*.py" = ["S101"]

[dependency-groups]
dev = [
    "prek>=0.3.8",
    "ruff>=0.15.8",
    "ty>=0.0.26",
]
